### ISSUE TITLE
Proposal: refresh button

### ISSUE THREAD

**Issue by KELiON** [npms-io/npms-www#147]
Hello! Thanks for doing npms – it is great tool! 

I use API in my [open-source project](https://cerebroapp.com) to manage plugins. Several times I had a situation when plugin ( === npm package) is updated and published to npm, but npms API result updated only after some time. 

I suppose that you don't have hooks from npm registry and you have to update your cache time to time and I'm thinking if it is possible to add refresh button to package page? Or maybe you have other ways to make updates faster?

**Comment by satazor** [comment]
This should be transparent because any published module gets higher priority and will be analyzed right away. But there's been some hicups with our queue module because it's not reconnecting to rabbitmq for some reason (on error).  I've fixed one issue here that maybe be related: https://github.com/npms-io/npms-analyzer/commit/43e1ef25854336ed3077e7afb9740439b3f65378

I've restarted the analyzer service and it's now analyzing modules again. Regarding your request, since this shouldn't be happening in first place, I do not want to introduce a "refresh" button since this should be transparent.

**Comment by KELiON** [comment]
@satazor Ok! How much time usually takes refresh of published versions? I.e. 1.5 hours ago I've published [cerebro-shell](https://www.npmjs.com/package/cerebro-shell)@0.1.2, but npms still shows version 0.1.1 as the latest

**Comment by satazor** [comment]
If the aforementioned problem didn't exist, it would take ~20sec maximum to appear, unless it failed to analyze for some reason (e.g.: github or node security project being down). In case of errors, the package gets queued again for later analysis.
